import { Category, NewsArticle, Ad } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'फुटबल', slug: 'football', color: '#2ecc71', created_at: new Date().toISOString() },
  { id: '2', name: 'क्रिकेट', slug: 'cricket', color: '#3498db', created_at: new Date().toISOString() },
  { id: '3', name: 'भलिबल', slug: 'volleyball', color: '#e67e22', created_at: new Date().toISOString() },
  { id: '4', name: 'बास्केटबल', slug: 'basketball', color: '#e31e24', created_at: new Date().toISOString() },
  { id: '5', name: 'eSports', slug: 'esports', color: '#9b59b6', created_at: new Date().toISOString() },
  { id: '6', name: 'अन्य खेल', slug: 'others', color: '#1abc9c', created_at: new Date().toISOString() },
];

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'नेपालले यूएईलाई हराउँदै आईसीसी क्रिकेट विश्वकप लिग-२ मा ऐतिहासिक जित हात पार्यो',
    slug: 'nepal-beat-uae-icc-cricket-world-cup-league-2',
    excerpt: 'त्रिवि क्रिकेट मैदान कीर्तिपुरमा भएको रोमाञ्चक खेलमा नेपालले यूएईलाई ४२ रनले पराजित गर्दै शीर्ष स्थान सुरक्षित गरेको छ।',
    content: `<p>नेपालले आईसीसी पुरुष क्रिकेट विश्वकप लिग-२ अन्तर्गतको रोमाञ्चक खेलमा संयुक्त अरब इमिरेट्स (यूएई) लाई ४२ रनले पराजित गरेको छ। कीर्तिपुरस्थित त्रिवि अन्तर्राष्ट्रिय क्रिकेट मैदानमा हजारौं नेपाली समर्थकमाझ भएको खेलमा नेपालले उत्कृष्ट प्रदर्शन गर्‍यो।</p>
    <p>टस जितेर पहिले ब्याटिङ गरेको नेपालले निर्धारित ५० ओभरमा ८ विकेट गुमाउँदै २७८ रनको बलियो योगफल तयार पारेको थियो। कप्तान रोहित पौडेलले उत्कृष्ट कप्तानी इनिङ्स खेल्दै सर्वाधिक ७७ रन बनाए भने कुशल भुर्तेलले आक्रामक ५४ रन जोडे।</p>
    <blockquote>"यो जित सम्पूर्ण नेपाली खेलप्रेमी दर्शकहरूको लागि समर्पित गर्दछौं, हाम्रो टिमको कडा मेहनत रंग ल्याएको छ।" - कप्तान रोहित पौडेल</blockquote>
    <p>जवाफी ब्याटिङमा उत्रिएको यूएई ४६.२ ओभरमा २३६ रनमै समेटियो। नेपालका लागि सन्दीप लामिछानेले ४ विकेट लिए भने करण केसी र सोमपाल कामीले समान २-२ विकेट हात पारे। यो जितसँगै नेपालको आगामी विश्वकप छनोटको सम्भावना थप मजबुत बनेको छ।</p>`,
    category_id: '2',
    category_name: 'क्रिकेट',
    category_slug: 'cricket',
    image_url: 'https://images.unsplash.com/photo-1531415074868-036b107e775a?q=80&w=1200&auto=format&fit=crop',
    author: 'खेलहब डेस्क',
    published_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    is_featured: true,
    is_breaking: true,
    is_published: true,
    views: 3420,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'news-2',
    title: 'सहिद स्मारक ‘ए’ डिभिजन लिग : मछिन्द्र क्लब र चर्च ब्वाइज बराबरीमा रोकिए',
    slug: 'machhindra-church-boys-draw-martyrs-memorial-league',
    excerpt: 'दशरथ रंगशालामा सम्पन्न प्रतिस्पर्धात्मक खेलमा दुबै टोलीले १-१ गोलको बराबरी खेल्दै अंक बाँडेका छन्।',
    content: `<p>सहिद स्मारक ‘ए’ डिभिजन लिग फुटबल प्रतियोगिता अन्तर्गत आज भएको खेलमा साविक विजेता मछिन्द्र फुटबल क्लब र चर्च ब्वाइज युनाइटेड १-१ गोलको बराबरीमा रोकिएका छन्।</p>
    <p>त्रिपुरेश्‍वरस्थित दशरथ रंगशालामा भएको खेलमा मछिन्द्रले पहिलो हाफको ३२औं मिनेटमा अग्रता लिएको थियो। तर दोस्रो हाफको ७०औं मिनेटमा चर्च ब्वाइजले उत्कृष्ट काउन्टर अट्याकमार्फत बराबरी गोल फर्कायो।</p>`,
    category_id: '1',
    category_name: 'फुटबल',
    category_slug: 'football',
    image_url: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=1200&auto=format&fit=crop',
    author: 'सुजन श्रेष्ठ',
    published_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    is_featured: true,
    is_breaking: false,
    is_published: true,
    views: 1840,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'news-3',
    title: 'नेपाल महिला भलिबल टिम काभा वुमन्स नेसन्स लिगको फाइनलमा प्रवेश',
    slug: 'nepal-women-volleyball-team-reaches-cava-final',
    excerpt: 'नेपालले सेमिफाइनलमा बलियो प्रतिद्वन्द्वी इरानलाई ३-१ को सेटमा पाखा लगाउँदै फाइनलमा स्थान पक्का गरेको हो।',
    content: `<p>राष्ट्रिय महिला भलिबल टोलीले काभा (CAVA) वुमन्स नेसन्स लिगको उपाधि भिडन्तका लागि स्थान पक्का गरेको छ। त्रिपुरेश्वरस्थित राष्ट्रिय खेलकुद परिषद्को कभर्डहलमा भएको सेमिफाइनलमा नेपालले इरानमाथि ३-१ को पुनरागमन जित निकाल्यो।</p>
    <p>नेपाली कप्तान अरुणा शाही र स्पाइकर उषा भण्डारीको प्रभावशाली खेलले दर्शकलाई रोमाञ्चित बनाएको थियो। फाइनल खेल आगामी शनिबार भारतविरुद्ध हुनेछ।</p>`,
    category_id: '3',
    category_name: 'भलिबल',
    category_slug: 'volleyball',
    image_url: 'https://images.unsplash.com/photo-1592656094267-764a45160876?q=80&w=1200&auto=format&fit=crop',
    author: 'खेलहब डेस्क',
    published_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    is_featured: true,
    is_breaking: true,
    is_published: true,
    views: 2950,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'news-4',
    title: 'नेपाल बास्केटबल लिग : टाइम्स इन्टरनेसनल क्लब शीर्ष स्थानमा कायमै',
    slug: 'nepal-basketball-league-times-club-stays-top',
    excerpt: 'टाइम्स क्लबले रोयल बास्केटबल क्लबलाई ८२-७४ अंकले हराउँदै लिगको शीर्ष स्थानमा आफ्नो पकड कायमै राखेको छ।',
    content: `<p>नेपाल बास्केटबल लिगमा टाइम्स इन्टरनेसनल क्लबले आफ्नो अपराजित यात्रालाई निरन्तरता दिएको छ। कभर्डहलमा सम्पन्न प्रतिस्पर्धात्मक खेलमा टाइम्सले रोयल क्लबलाई ८२-७४ स्कोरले पराजित गर्‍यो।</p>`,
    category_id: '4',
    category_name: 'बास्केटबल',
    category_slug: 'basketball',
    image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?q=80&w=1200&auto=format&fit=crop',
    author: 'प्रदीप कार्की',
    published_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    is_featured: true,
    is_breaking: false,
    is_published: true,
    views: 1120,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'news-5',
    title: 'पबजी मोबाइल ग्लोबल च्याम्पियनसिपमा नेपाली टोली डीआरएस गेमिङ उत्कृष्ट पाँचमा',
    slug: 'pubg-mobile-drs-gaming-top-5-global',
    excerpt: 'नेपालको अग्रणी ई-स्पोर्ट्स टोली डीआरएस गेमिङले अन्तर्राष्ट्रिय मञ्चमा नेपालको झण्डा फहराउँदै शीर्ष ५ भित्र पर्न सफल भएको छ।',
    content: `<p>नेपाली ई-स्पोर्ट्स इतिहासमा अर्को ठूलो सफलता थपिएको छ। विश्व प्रसिद्ध पबजी मोबाइल ग्लोबल च्याम्पियनसिप (PMGC) मा नेपालको प्रतिनिधित्व गर्दै डीआरएस गेमिङ शीर्ष ५ भित्र स्थान बनाउन सफल भएको छ।</p>`,
    category_id: '5',
    category_name: 'eSports',
    category_slug: 'esports',
    image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop',
    author: 'अमित गुरुङ',
    published_at: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    is_featured: true,
    is_breaking: false,
    is_published: true,
    views: 4500,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'news-6',
    title: 'साफ यू-२० च्याम्पियनसिप : नेपाली युवा टोलीको तयारी तीव्र',
    slug: 'saff-u20-nepal-team-preparations',
    excerpt: 'आगामी महिना हुने साफ यू-२० च्याम्पियनसिपका लागि नेपाली युवा फुटबल टोली एन्फा कम्प्लेक्स सातदोबाटोमा कडा प्रशिक्षणमा जुटेको छ।',
    content: `<p>अखिल नेपाल फुटबल संघ (एन्फा) ले साफ यू-२० च्याम्पियनसिपको लागि बन्द प्रशिक्षण तीव्र पारेको छ। मुख्य प्रशिक्षकले खेलाडीहरूको फिटनेस र रणनीतिक खेलमा जोड दिएका छन्।</p>`,
    category_id: '1',
    category_name: 'फुटबल',
    category_slug: 'football',
    image_url: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?q=80&w=1200&auto=format&fit=crop',
    author: 'खेलहब डेस्क',
    published_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    is_featured: false,
    is_breaking: false,
    is_published: true,
    views: 890,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'news-7',
    title: 'नेपाल प्रिमियर लिग (NPL) को नयाँ संस्करण आगामी मंसिरमा हुने घोषणा',
    slug: 'nepal-premier-league-npl-announced',
    excerpt: 'नेपाल क्रिकेट संघ (क्यान) ले बहुप्रतीक्षित नेपाल प्रिमियर लिगको मिति सार्वजनिक गर्दै ८ फ्रेन्चाइज टोलीको सहभागिता निश्चित गरेको छ।',
    content: `<p>नेपाल क्रिकेट संघ (क्यान) ले नेपाल प्रिमियर लिग (NPL) को नयाँ संस्करण आगामी मंसिरमा भव्यताका साथ आयोजना गर्ने घोषणा गरेको छ। यस प्रतियोगितामा देशका विभिन्न शहरहरूको प्रतिनिधित्व गर्ने ८ टोलीहरू सहभागी हुनेछन्।</p>`,
    category_id: '2',
    category_name: 'क्रिकेट',
    category_slug: 'cricket',
    image_url: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=1200&auto=format&fit=crop',
    author: 'खेलहब डेस्क',
    published_at: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    is_featured: false,
    is_breaking: true,
    is_published: true,
    views: 5210,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'news-8',
    title: '१०औं राष्ट्रिय खेलकुद कर्णाली प्रदेशमा गर्ने तयारी अन्तिम चरणमा',
    slug: '10th-national-games-karnali-preparations',
    excerpt: 'राष्ट्रिय खेलकुद परिषद्ले सुर्खेत रंगशाला निर्माण तीव्र गतिमा भइरहेको र समयमै प्रतियोगिता सञ्चालन हुने जनाएको छ।',
    content: `<p>कर्णाली प्रदेशमा आयोजना हुन लागेको १०औं राष्ट्रिय खेलकुद प्रतियोगिताको तयारी अन्तिम चरणमा पुगेको छ। राष्ट्रिय खेलकुद परिषद् (राखेप) ले पूर्वाधार निर्माण र व्यवस्थापनको काम तीव्रताका साथ अघि बढेको जानकारी दिएको छ।</p>`,
    category_id: '6',
    category_name: 'अन्य खेल',
    category_slug: 'others',
    image_url: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=1200&auto=format&fit=crop',
    author: 'खेलहब डेस्क',
    published_at: new Date(Date.now() - 1000 * 60 * 900).toISOString(),
    is_featured: false,
    is_breaking: false,
    is_published: true,
    views: 740,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_ADS: Ad[] = [
  {
    id: 'ad-1',
    name: 'Header Banner Ad',
    position: 'header',
    image_url: null,
    link_url: 'https://khelhubnepal.com',
    code: '<div style="background:linear-gradient(135deg,#1a2357,#e31e24);color:white;padding:12px 24px;border-radius:6px;text-align:center;font-weight:700;font-size:14px;letter-spacing:1px;display:flex;align-items:center;justify-content:center;gap:10px;height:50px;"><span>🔥 KhelHub Nepal Official Ads Space</span><span style="background:rgba(255,255,255,0.2);padding:2px 8px;border-radius:4px;font-size:11px;">Advertise Here</span></div>',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ad-2',
    name: 'Sidebar Ad',
    position: 'sidebar',
    image_url: null,
    link_url: 'https://www.youtube.com/@KhelhubNepal',
    code: '<div style="background:linear-gradient(180deg,#1a2357 0%,#0f1535 100%);color:white;padding:24px 16px;border-radius:8px;text-align:center;border:1px solid rgba(227,30,36,0.4);"><div style="font-size:32px;margin-bottom:8px;">📺</div><div style="font-weight:800;font-size:16px;color:#ff3a40;margin-bottom:4px;">KhelHub Nepal</div><p style="font-size:12px;opacity:0.8;margin-bottom:14px;">हाम्रो आधिकारिक युट्युब च्यानल सब्स्क्राइब गर्नुस्!</p><a href="https://www.youtube.com/@KhelhubNepal" target="_blank" rel="noopener noreferrer" style="display:inline-block;background:#e31e24;color:white;padding:8px 18px;border-radius:4px;font-weight:700;font-size:13px;text-decoration:none;">Subscribe Now 🔴</a></div>',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ad-3',
    name: 'Facebook Community Ad',
    position: 'sidebar',
    image_url: null,
    link_url: 'https://www.facebook.com/profile.php?id=61557354328245',
    code: '<div style="background:#1877f2;color:white;padding:20px 16px;border-radius:8px;text-align:center;"><div style="font-size:28px;margin-bottom:6px;">👍</div><div style="font-weight:700;font-size:15px;margin-bottom:4px;">Facebook मा जोडिनुस्</div><p style="font-size:12px;opacity:0.9;margin-bottom:12px;">ताजा खेलकुद अपडेट र भिडियोहरू हेर्न हाम्रो पेज फलो गर्नुस्</p><a href="https://www.facebook.com/profile.php?id=61557354328245" target="_blank" rel="noopener noreferrer" style="display:inline-block;background:white;color:#1877f2;padding:6px 16px;border-radius:4px;font-weight:700;font-size:12px;text-decoration:none;">Follow Page →</a></div>',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ad-4',
    name: 'Home Banner Ad',
    position: 'footer',
    image_url: null,
    link_url: 'https://khelhubnepal.com',
    code: '<div style="background:linear-gradient(90deg,#0f1535,#1a2357,#e31e24);color:white;padding:16px;border-radius:6px;text-align:center;font-weight:700;font-size:14px;letter-spacing:1px;">🏆 खेलकुद समाचार र विज्ञापनका लागि KhelHub Nepal लाई सम्पर्क गर्नुस् : info@khelhubnepal.com</div>',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
